#! /usr/bin/env bash

src="./.cdf_script"
src_diff="$src/existing_difficulties"
src_temp="$src/c_template.c"

initial_checks(){
	if [[ !(-d $src) ]]; then
		echo "Run './cdf init' to create the structure needed."
		exit
	fi
}


init(){
	#Creates the .cdf_script folder
	$(mkdir $src)
	#Creates the existing_difficulties file
	$(touch $src_diff)
	#Creates the c_template.c file
	$(touch $src/c_template.c);
	$(echo $'/*\n\n*/\n\n#include <stdio.h>\n\nint main(){\n\n\n\n\treturn 0;\n}' >> $src/c_template.c)
	#Move the cdf script to .cdf_script folder
	$(mv ./cdf $src)
}


get_difficulty(){
	local difficulty=$(head -n 3 $1 | tail -n 1)
	
	echo "$difficulty"
}


exist_difficulty(){
	#if [[ !(-e ./.order_files/existing_difficulties) ]]; then
	#	$(touch ./.order_files/existing_difficulties)
	#fi
	
	difficulties=($(cat $src_diff))

	#This for loop iterates through all difficulties array values storing then into i
	for i in "${difficulties[@]}"; do 
		if [[ "$i" == "$1" ]]; then
			echo "1"
			return
		fi
	done

	echo "0"
	return
}

new(){

	initial_checks

	if [[ !(-e $src_temp) ]]; then
		$(touch $src_temp);
		$(echo $'/*\n\n*/\n\n#include <stdio.h>\n\nint main(){\n\n\n\n\treturn 0;\n}' >> $src_temp)
	fi


	if [[ $1 ]]; then
		$(cp $src_temp ./$1.c)
	else
		$(cp $src_temp .)
	fi
}


order(){
	#Checks if the .order_files folder exists at the current folder
	initial_checks

	#Gets number of files with .c extension
	nfiles=$(ls *.c | wc -l)

	#Creates an array with all files ending with .c extension
	files=($(ls *.c))


	for ((i = 0 ; i < nfiles ; i++)); do
		difficulty="$(get_difficulty ${files[$i]})"
		exists=$(exist_difficulty "$difficulty")
		if [[ "1" == "$exists" ]];  then
			$(mv "${files[$i]}" "./$difficulty")
		else
			echo "Create new difficulty folder ($difficulty) for ${files[$i]} file? [y/n]"
			read ans
			if [[ "$ans" == "y" ]]; then
				$(mkdir "$difficulty")
				$(echo "$difficulty" >>  $src_diff)
				$(mv "${files[$i]}" "./$difficulty")
			fi
		fi
	done

}


case $1 in

	init)
	init
	;;

	new)
	new "$2"
	;;

	*)
	order
	;;

esac